service: aws-rest-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  # memorySize: 128 # mb
  # timeout: 5 # seconds

functions:
  addNumbers:
    handler: src/numbers.addNumbers
    name: addNumbers
    events:
      - http:
          path: add
          method: POST

  hello:
    handler: src/handler.hello
    name: hello
    events:
      - http:
          path: hello
          method: GET

  temp:
    handler: src/temp.handler
    name: temp
    events:
      - http:
          path: temp
          method: GET

  question:
    handler: src/question.handler
    dependsOn: SNSHelloEvent
    events:
      - sns:
          arn: !Ref SNSHelloEvent
          topicName: hello-event

# Serverless plugins
plugins:
  - serverless-plugin-typescript

# Resources your functions use
resources:
  Resources:
    # SNS Topics
    SNSHelloEvent:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Question Event Topic
        TopicName: question-event

